export const TYPE = {
  CONNECT: "connect",
  DISCONNECT: "disconnect",
  CREATE_ROOM: "CREATE_ROOM",
  JOIN_ROOM: "JOIN_ROOM",
  LEAVE_ROOM: "LEAVE_ROOM",
  SEND_MESSAGE: "SEND_MESSAGE",
  CHARACTER_MOVE: "CHARACTER_MOVE",
};
